# Default configuration (PHANTOM paper settings)
debug: false
verbose: false
skip_existing: false
n_processes: 1
data_root_dir: "../data/raw_data/"
processed_data_root_dir: "../data/processed_data/"
demo_name: ""

# Processing settings
mode: ["bbox"]  # Default processing mode - must be one of: bbox, hand2d, hand3d, hand_segmentation, arm_segmentation, action, smoothing, hand_inpaint, robot_inpaint, all
demo_num: null  # Process specific demo number (null = process all)

# Additional settings
debug_cameras: []

# PHANTOM paper configuration (default)
input_resolution: 1080
output_resolution: 240
robot: "Panda"
gripper: "Robotiq85"
square: true
epic: false
bimanual_setup: "single_arm"
target_hand: "left"
constrained_hand: true
depth_for_overlay: true
render: false
camera_intrinsics: "camera/camera_intrinsics_HD1080.json"
camera_extrinsics: "camera/camera_extrinsics.json"
